Millorar dockerització (#61)
* Millores a la Dockerfile

* Canviada imatge de Docker base python:3.10.3 per python:3.10-slim

La lògica darrera el canvi és que 1. Millor no especificar la versió bugfix 2. La versió slim fa les imatges molt més lleugeres

* Proves per afegir workflow test imatge Docker

* Més proves per workflow amb Docker

* Afegit comentari d'aclariment al workflow de Docker

* Afegit docker compose up al workflow de Docker

També volem comprovar que l'imatge s'aixeca correctament

* Fix: és docker compose config, no docker compose check

* Fix en workflow de Docker

* Modificat tests de la Dockerització

* Actualitzat versio hadolint al workflow

* Afegida comprovacio correcte funcionament de collectstatic

* Fix: arreglada versio d'Action de hadolint

* Arreglat test de Docker dels Github workflows

* Format fix

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,4 @@
-FROM python:3.11.4 as python-base
+FROM python:3.11-slim as python-base
 
 # ensures that the python output is sent straight to terminal
 ENV PYTHONUNBUFFERED=1 \
@@ -11,9 +11,8 @@ ENV PYTHONUNBUFFERED=1 \
   PIP_NO_CACHE_DIR=off \
   PIP_DISABLE_PIP_VERSION_CHECK=on \
   PIP_DEFAULT_TIMEOUT=100 \
-  # poetry. Using 1.2.2 bc is compatible with pyproject.toml files generated by
-  # either poetry versions prior to 1.2.2 and versions 1.3+
-  POETRY_VERSION=1.2.2 \
+  # poetry.
+  POETRY_VERSION=1.7.0 \
   # make poetry install to this location
   POETRY_HOME="/opt/poetry" \
   # make poetry create the virtual environment in the project's root
@@ -29,32 +28,46 @@ ENV PYTHONUNBUFFERED=1 \
 # prepend poetry and venv to path
 ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
 
+
+###############################################################################
 # `builder-base` stage is used to build deps + create our virtual environment
+###############################################################################
 FROM python-base as builder-base
-RUN set -x \
-  # deps for installing poetry
-  && buildDeps=" \
+
+# 1. -e causes a script to exit if any of the processes it calls generate a
+#    non-zero return code
+# 2. -o pipefail  makes a pipe chain of scripts return a non-zero code
+#    if *any* of the inbetween scripts returned a non-zero code.
+SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
+
+# System deps
+# hadolint ignore=DL3008
+RUN apt-get update && apt-get upgrade -y \
+  && apt-get install -y --no-install-recommends -y \
   curl \
-  " \
-  && apt-get update && apt-get install -y --no-install-recommends $buildDeps \
-  && rm -rf /var/lib/apt/lists/* \
-  # install poetry - respects $POETRY_VERSION & $POETRY_HOME
-  && curl -sSL https://install.python-poetry.org | python \
-  && apt-get purge -y --auto-remove $buildDeps
+  # Install `poetry` package manager - respects $POETRY_VERSION & $POETRY_HOME:
+  # https://github.com/python-poetry/poetry
+  && curl -sSL https://install.python-poetry.org | python - \
+  && poetry --version \
+  # Cleaning cache:
+  && apt-get purge -y --auto-remove curl \
+  && apt-get clean -y && rm -rf /var/lib/apt/lists/*
 
 # copy project requirement files here to ensure they will be cached.
 WORKDIR $PYSETUP_PATH
 COPY poetry.lock pyproject.toml ./
+# hadolint ignore=DL3008
 RUN set -x \
-  && buildDeps="git" \
   && apt-get update \
-  && apt-get install -y --no-install-recommends $buildDeps \
+  && apt-get install -y --no-install-recommends git \
   && poetry install --only main --no-ansi \
-  && apt-get purge -y --auto-remove $buildDeps \
+  && apt-get purge -y --auto-remove git \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/*
 
+###############################################################################
 # `development` image is used during development / testing
+###############################################################################
 FROM python-base as development
 WORKDIR $PYSETUP_PATH
 
@@ -69,7 +82,9 @@ RUN poetry install
 WORKDIR /srv
 CMD ["gunicorn", "conf.wsgi:application", "--bind", "0.0.0.0:8000", "--reload"]
 
+###############################################################################
 # `production` image used for runtime
+###############################################################################
 FROM python-base as production
 
 COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH
